Added simple view for single fields
mireo91/RepeatableFields pull request #26
Opened 2024-05-08 11:50 UTC by vcg-development

This PR adds a minimalistic view if you just need a single repeatable field instead of a group of fields.

![simpleview](https://github.com/mireo91/RepeatableFields/assets/136594881/b8d6beae-ee04-446a-ba86-35150193492a)

2024-05-08 12:00 UTC, mireo91 requested changes
From this commit I see only changes on Readme
nothing else was changed

2024-05-08 13:51 UTC, vcg-development commented
@mireo91 I'm sorry. I forgot to push the changes. It should be visible now. :)

2024-05-14 18:48 UTC, jonnitto requested changes

2024-05-14 18:48 UTC, jonnitto commented on Resources/Private/Backend/RepeatableField/src/View/Repeatable.js
> +		const isPredefined = options.predefinedProperties && options.predefinedProperties[idx] ? true : false;
Please use spaces
```suggestion
     const isPredefined = options.predefinedProperties && options.predefinedProperties[idx] ? true : false;
```

2024-06-03 13:36 UTC, vcg-development commented
@jonnitto Done

2024-06-03 16:46 UTC, jonnitto commented on Resources/Private/Backend/RepeatableField/src/View/Repeatable.js
> +    }
You can also remove this `else` block, as the `if` before has a `return` statement

```suggestion
    }
 
    return (
        <div className={style.wrapper}>
          <div class={style.buttons}>
            {!isPredefined && options.controls.move && currentValue.length > 1 ? (
              <DragHandle />
            ) : (
              ""
            )}
            {!isPredefined && options.controls.remove && allowRemove ? (
              <IconButton
                onClick={() => this.handleRemove(idx)}
                className={style.delete}
                icon="trash"
              />
            ) : (
              ""
            )}
          </div>
          {this.getProperties(idx)}
        </div>
      );
```

2024-06-18 09:00 UTC, vcg-development commented
@jonnitto Is there still something I can improve or is it ready to be merged?

2024-06-18 10:33 UTC, jonnitto commented
No, we've to wait for @mireo91

2024-06-18 10:56 UTC, jonnitto commented
@vcg-development The fields looks a bit unaligned. I think there is some more CSS work needed…

https://github.com/mireo91/RepeatableFields/assets/4510166/dd57342c-a688-4221-887a-baf35b8967d6

2024-06-18 12:55 UTC, vcg-development commented
> @vcg-development The fields looks a bit unaligned. I think there is some more CSS work needed…
> 
>  CleanShot.2024-06-18.at.12.55.08.mp4

We'll have a look at it.

2024-07-08 09:07 UTC, vcg-development commented
@jonnitto I just tried to fix the problem but it's looking good on my end. Can you please send me an example yaml property so I can test it?

2024-10-16 07:34 UTC, jonnitto commented
@vcg-development If it ok for you I would integrate this into this PR #28

2024-10-25 08:04 UTC, vcg-development commented
Sure. Thank you!

2024-10-28 08:17 UTC, jonnitto commented
> Sure. Thank you!

Already done 😉

2024-10-29 10:13 UTC, jonnitto commented
@mireo91 When #28 is merged, you can close this one

2024-10-29 12:28 UTC, closed without merging

2024-10-29 12:38 UTC, mireo91 commented
@vcg-development new release v2.2.2 should contain your modifications https://github.com/mireo91/RepeatableFields/releases/tag/v2.2.2
Many thanks and sorry for delays